name: Leanside
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  hard_wrap: false
pygments: true
permalink: /:year/:month/:title/

author:
  name: Kjell
  email: kjell@leanside.com
production_url: http://leanside.com

prose:
  rooturl: '_posts'
